# Generated by Django 3.1.2 on 2020-10-31 02:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20201025_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 2, 6, 55, 140902, tzinfo=utc)),
        ),
    ]
